In [2]:
import numpy as np
import time

In [3]:
# #execution performance
# size=10_000_000
# #time measure
# py_list=list(range(size))
# start=time.time()
# sq_list=[x**2 for x in py_list]
# end=time.time()
# print(f"python list time={end-start}seconds")

# #numpy array

# np_arr=np.array(py_list)
# start=time.time()
# sq_array=np_arr**2
# end=time.time()
# print(f"numpy array time={end-start}seconds")





In [4]:
# #memory
# import sys
# print(f"python list size={sys.getsizeof(py_list)*len(py_list)} bytes")

# print(f"numpy array size={np_arr.nbytes} bytes")

In [5]:
#create -from list
arr=np.array([1,2,3,4])
print(arr,type(arr))

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.shape)
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2d,arr2d.shape)

[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [6]:
#creeatteh 2d array with prefill with 0
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

arr2=np.ones((5,5))
print(arr2,arr2.shape)

arr3=np.full((5,4),1000)
print(arr3,arr3.shape)
arr4=np.eye(3)
print(arr4,arr4.shape)


arr5=np.arange(1,11,2)
print(arr5,arr5.shape)



arr6=np.linspace(2,100,3)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (5, 5)
[[1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]] (5, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  2.  51. 100.] (3,)


In [7]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr[0][0])
print(arr[1][2])

#fancong indexing
arr22=np.array([1,2,3,4,5])
idx=[0,1,2]
print(arr22[idx])


#boolean indexing

arr=np.array([1,2,3,4,5,6])
print(arr[arr>2])
print(arr[arr%2==0])
print(arr[arr%2!=0])


1
6
[1 2 3]
[3 4 5 6]
[2 4 6]
[1 3 5]


In [9]:
#slicing

arr=np.array([1,3,2,4,5])
print(arr[1:4])
print(arr[:4])


#slicing in numpy array
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
sub_arr[1]=2000
print(sub_arr)
print(arr)


[3 2 4]
[1 3 2 4]
[   2 2000]
[   1    2 2000    4    5]


In [10]:
#data types in numpy
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [14]:
#broadcasting

arr=np.array([1,2,3,4,5])
arr2=np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)
print(arr+arr2)

(5,)
(2, 5)
[[ 7  9 11 13 15]
 [ 2  4  6  8 10]]


In [19]:
#normailze

arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
mormalized_arr=(arr-mean)/std_dev
print(mormalized_arr)
print(mean)
print(std_dev)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [21]:
#mathematical functuion

#agregation
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.square(arr))
print(np.log10(arr))
print(np.unique(arr))
print(np.sort(arr))

15
120
1
3.0
1.4142135623730951
[ 1  4  9 16 25]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[1 2 3 4 5]
[1 2 3 4 5]
